set dotenv-load := true

run:
  yarn dev --port 7277

build:
  PUBLIC_API_BRIDGE_BASE_URL=https://osu-api-bridge.ameo.dev yarn build

deploy:
  phost update osu-map patch build

build-and-deploy:
  just build
  just deploy
